disabled_rules: # rule identifiers to exclude from running
  - empty_enum_arguments
  - file_length
  - implicit_return
  - nesting
  - line_length
  - todo
  - trailing_comma
  - inclusive_language
  - redundant_type_annotation
  - cyclomatic_complexity
  - number_separator
  - multiple_closures_with_trailing_closure
opt_in_rules: # some rules are only opt-in
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_object_literal
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - file_header
  - file_name_no_space
  - first_where
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - object_literal
  - overridden_super_call
  - override_in_extension
  - private_action
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - static_operator
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - yoda_condition
included: # paths to include during linting. `--path` is ignored if present.
  - Alarm-Wakeup
  - Alarm-WakeupTests
  - PAlarm-WakeupUITests
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Project/R.generated.swift

analyzer_rules:
  - unused_import
  - unused_declaration

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly. Give warning only for force casting

force_try:
  severity: warning # explicitly. Give warning only for force try

type_body_length:
  - 300 # warning
  - 400 # error

function_parameter_count:
  warning: 8

identifier_name:
  min_length:
    warning: 3
  max_length:
    warning: 50
    error: 60
  excluded:
    - x
    - y
    - on
    - id
    - qr

large_tuple:
  warning: 4
  error: 5
   
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 50
  allowed_symbols: "_"

overridden_super_call:
  excluded:
    - setUp()
    - tearDown()
    - setUpWithError()
    - tearDownWithError()
    
reporter: "xcode"
